spring:
  config:
    activate:
      on-profile: location
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:mysql://localhost:3306/locationdb?allowPublicKeyRetrieval=true&characterEncoding=UTF-8
    username: 
    password: 
  jpa:
    open-in-view: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update  # 스키마 자동 생성
    show-sql: true      # SQL 쿼리 출력
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
        format_sql: true  # SQL pretty print
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 574447307453-3k73gp7a11a251ptlfr948u8o18evba5.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
  sql:
    init:
      data-locations: classpath*:db/h2/data.sql

#AWS S3
cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
    s3:
      bucket: bobimage # 버킷 이름 수정
    stack:
      auto-: false
    region:
      static: ap-northeast-2

mail:
  address:
    admin: admin@gmail.com    # jwt 사용할때 필요

jwt:
  key:
    secret: bobfriend132412341234123412341234123423412341234123412341234114123411234123412341234
  access-token-expiration-minutes: 40
  refresh-token-expiration-minutes: 420
